[build]
  command = "pnpm docs:build"
  publish = ".vitepress/dist"

[[redirects]]
from = "https://sad-shirley-3d5d8f.netlify.app/*"
to = "https://granddaifuku.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://sad-shirley-3d5d8f.netlify.app/*"
to = "https://granddaifuku.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://granddaifuku.com/*"
to = "https://granddaifuku.com/:splat"
status = 301
force = true
