[build]
  command = "pnpm run docs:build"
  publish = "docs/.vitepress/dist"

[[redirects]]
from = "https://sad-shirley-3d5d8f.netlify.app/*"
to = "https://www.granddaifuku.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://sad-shirley-3d5d8f.netlify.app/*"
to = "https://www.granddaifuku.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.granddaifuku.com/*"
to = "https://www.granddaifuku.com/:splat"
status = 301
force = true
